### PR TITLE
Fix LDPC Initialization Bug

### LINKED ISSUE #21: LPDC(1440,1056) and LDPC(1440,1344). Can anyone tell me how to find or make the H- and G-Matrix for LDPC-coding ?
from copy import deepcopy
from hermespy.core import ConsoleMode, dB
import numpy as np
from hermespy.channel import Channel, IdealChannel
from hermespy.fec.aff3ct import TurboCoding, BCHCoding, ReedSolomonCoding, LDPCCoding
from hermespy.tools import db2lin
from hermespy.simulation import Simulation
from hermespy.modem import RootRaisedCosineWaveform
from hermespy.modem import TransmittingModem, ReceivingModem, OFDMWaveform, GridResource, GridElement, SymbolSection, BitErrorEvaluator, BlockErrorEvaluator, FrameErrorEvaluator, ThroughputEvaluator

simulation = Simulation()
num_iterations = 20
h_source_path = "C:\\Users\\adaiha\\Desktop\\Hermespy\\H_matrix_1344_1440.alist"
g_save_path = "C:\\Users\\adaiha\\Desktop\\Hermespy\\g_matrix.alist"   
enable_syndrome_checking = True
min_num_iterations = 10
ldpc_coder = LDPCCoding(num_iterations, h_source_path,
                        g_save_path, enable_syndrome_checking, min_num_iterations)

data_block_size=1344
tx_device = simulation.new_device()
rx_device = simulation.new_device()
data = np.random.randint(0, 2, data_block_size)
waveform = RootRaisedCosineWaveform(modulation_order=16, oversampling_factor=2, num_preamble_symbols=0, num_data_symbols=100, symbol_rate=1e9)

tx_modem = TransmittingModem()
tx_modem.random_bits = data
tx_modem.encoder_manager.add_encoder(ldpc_coder)
tx_modem.waveform = deepcopy(waveform) 
tx_device.transmitters.add(tx_modem)

channel = IdealChannel()
simulation.scenario.set_channel(tx_device, rx_device, channel)

rx_modem = ReceivingModem()
rx_modem.waveform = deepcopy(waveform)
rx_modem.encoder_manager.add_encoder(ldpc_coder)
rx_device.receivers.add(rx_modem)

simulation.new_dimension('noise_level', dB(0, 2), rx_device)
simulation.add_evaluator(BitErrorEvaluator(tx_modem, rx_modem))
simulation.num_samples, simulation.min_num_samples = 10000, 9000
simulation.plot_results = True
simulation.num_actors = 2
simulation.results_dir = simulation.default_results_dir()

simulation.run()

### PR DESCRIPTION
**Pull request by adlerjan**
Fixes the LDPC initialization bug by removing the bit position argument.

Fixes #21

### CODE REVIEW

**Comment by adlerjan** [comment]
@IhabAdarbeh could you install this branch and check if you can successfully run an LDPC coding?

**Comment by IhabAdarbeh** [comment]
I have tried to run LDPC coding with different ALIST files, but I’m still encountering the same error

**Comment by adlerjan** [comment]
Alright, I didn't try running a full simulation, there was also a pickeling issue.
Please pull and give it another shot, sorry for the inconvenience :smile:

**Comment by IhabAdarbeh** [comment]
it only worked for the h-matrix file you used, if I try to use another file it shows an error again

**Comment by adlerjan** [comment]
@IhabAdarbeh I added a few more alist files, all of them work in the unit test and the script you provided in the issue.

If you checked out the current branch, activated the correct virtual environment and re-built the binaries by running `pip install -ve .`, the following code should run just fine:

```python
from copy import deepcopy

from hermespy.core import dB
from hermespy.channel import IdealChannel
from hermespy.fec import LDPCCoding, Scrambler3GPP
from hermespy.simulation import Simulation
from hermespy.modem import RootRaisedCosineWaveform, TransmittingModem, ReceivingModem, GridElement, SymbolSection, BitErrorEvaluator


simulation = Simulation()
num_iterations = 20
h_source_path = "D:\\hermespy\\submodules\\affect\\conf\\dec\\LDPC\\MACKAY_504_1008.alist"
enable_syndrome_checking = True
min_num_iterations = 10
ldpc_coder = LDPCCoding(num_iterations, h_source_path, "", enable_syndrome_checking, min_num_iterations)

tx_device = simulation.new_device()
rx_device = simulation.new_device()
waveform = RootRaisedCosineWaveform(modulation_order=16, oversampling_factor=2, num_preamble_symbols=0, num_data_symbols=256, symbol_rate=1e9)

tx_modem = TransmittingModem()
tx_modem.encoder_manager.add_encoder(ldpc_coder)
tx_modem.encoder_manager.add_encoder(Scrambler3GPP())
tx_modem.waveform = deepcopy(waveform)
tx_device.transmitters.add(tx_modem)

channel = IdealChannel()
simulation.scenario.set_channel(tx_device, rx_device, channel)

rx_modem = ReceivingModem()
rx_modem.waveform = deepcopy(waveform)
rx_modem.encoder_manager.add_encoder(ldpc_coder)
rx_modem.encoder_manager.add_encoder(Scrambler3GPP())
rx_device.receivers.add(rx_modem)

simulation.new_dimension('noise_level', dB(-10, 0, 10, 20, 30), rx_device)
ber = BitErrorEvaluator(tx_modem, rx_modem)
simulation.add_evaluator(ber)
simulation.num_samples = 10000
simulation.min_num_samples = 900
simulation.plot_results = True
simulation.results_dir = simulation.default_results_dir()

simulation.run()
```

**Pull request merged**
